FROM python:3.10.10-slim

ENV LC_ALL "C.UTF-8"
ENV LANG "C.UTF-8"

RUN apt-get update && apt-get install -y \
   libcairo2-dev gcc pkg-config libgirepository1.0-dev postgresql postgresql-contrib openssl \
   libssl-dev libcurl4-openssl-dev build-essential git libpq-dev openssh-client libgl1 \
   && rm -rf /var/lib/apt/lists/*

# Download public key for github.com
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

#Create a virtual environment we can copy over
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt ./
COPY requirements.dev.txt ./
RUN pip3 install --upgrade setuptools pip
RUN --mount=type=ssh pip3 install --ignore-installed --no-cache-dir -r requirements.dev.txt

# Takes care of all packages needed for open-telemetry
RUN opentelemetry-bootstrap --action=install

WORKDIR /tests/
COPY . ./
CMD python3 -m pytest

# Run specific file
# CMD python3 -m pytest tests/graphql_entities/sections/test_dataloaders.py

